# This file is added to image as /etc/cloud/cloud.cfg.d/99-armbian-boot.cfg

# configure cloud-init for non cloud. /var/lib/cloud/seed/nocloud is seeded with symlinks to /boot
datasource_list: [ NoCloud, None ]
datasource:
  NoCloud:
    dsmode: net

